### ISSUE TITLE
阿里云容器部署，时不时会Timeout was reached

### ISSUE THREAD

**Issue by funlake** [laruence/yar#103]
我部署了两个容器A和B,A用yar调用B提供的服务，现在是10次调用，有50%几率会抛出Timeout was reached的异常，其余50%请求是正确返回的。

**Comment by funlake** [comment]
curl 版本 curl 7.35.0 (x86_64-unknown-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.28

**Comment by laruence** [comment]
说明网络环境不好, 你可以适当增大timeout值

**Comment by funlake** [comment]
谢谢鸟哥，问题已确定，不是yar的问题，是容器集群的dns缓存问题。
