### ISSUE TITLE
client设置api地址的时候能不能加上host设置

### ISSUE THREAD

**Issue by snowshadow** [laruence/yar#105]
我遇到的问题是本机client请求本机server，想通过localhost；但是80端口下有很多virual host，需要指定一个server name。
希望能增加这个设置。

**Comment by laruence** [comment]
你就直接写url作为api地址啊, 我没明白你的问题?

**Comment by snowshadow** [comment]
类似于curl -H "HOST:xxx.com" "http://127.0.0.1:80/api"

**Comment by laruence** [comment]
可以在host里设置一些域名解析，后续改host就可以了
