### ISSUE TITLE
yar要结合zipkin怎么做，或者有无更好的分布式rpc追踪方案。

### ISSUE THREAD

**Issue by funlake** [laruence/yar#107]
我看了zipkin的phpkin的demo代码，需要往http请求头加入一系列参数，yar既然是基于http的，可否实现个自定义http头的方法，可让开发者灵活设置http额外的请求头？

或者有其它方式，无需修改源码？

**Comment by laruence** [comment]
Yar不是只基于HTTP, 还有基于Socket的, 所以不能支持自定义HTTP头, 如果需要你可以放到URL的query参数中去>

**Comment by funlake** [comment]
好的，谢谢鸟哥。
