### ISSUE TITLE
yar能否支持客户端自定义header头部呢

### ISSUE THREAD

**Issue by tangyouyou** [laruence/yar#108]
现在遇到个问题，后续是否考虑增加自定义header头部?

**Comment by tangyouyou** [comment]
目前在搭建项目监控，需要针对yar做一系列监控，因此希望yar_client可设置自定义header头部。
比如yar_client->setHeader('key', 'value');
在php中可通过$_SERVER获取相应的header头部即可。

**Comment by laruence** [comment]
我提交了一个更新, 可以支持设置自定义Header
````
$client->setOpt(YAR_OPT_HEADER, array("key: val", "key1: val"));
````
你试试

**Comment by tangyouyou** [comment]
可以正常使用了，非常感谢鸟哥。

**Comment by laruence** [comment]
恩, 那我先关闭这个issue, 如果发现什么问题可以再提Issue
