### ISSUE TITLE
configure: error: Please reinstall the libcurl distribution - easy.h should be in <curl-dir>/include/curl/

### ISSUE THREAD

**Issue by sansanboy** [laruence/yar#111]
ubutun 17
已经安装 
apt-get install curl
apt-get install libcurl4-gnutls-dev
还是这个错误
configure: error: Please reinstall the libcurl distribution - easy.h should be in <curl-dir>/include/curl/

**Comment by iliubang** [comment]
@sansanboy ubuntu17中libcurl实际上被安装在了`/usr/include/x86_64-linux-gnu/curl`路径，你可以执行`sudo ln -s /usr/include/x86_64-linux-gnu/curl /usr/include/`后再编译

**Comment by ranchoyang** [comment]
@iliubang 很感谢，问题解决了，我尝试安装了提示的组件，也尝试做了Libcurl.so的链接，都没有解决，通过你提供的方法解决了，再次感谢

**Comment by shouhuori** [comment]
可以使用源码安装，然后手动指定curl路径。我的环境是macOS，没有/usr/include文件夹
`pecl download yar`
`cd yar-2.0.6`
`./configure --with-php-config=/usr/local/opt/php/bin/php-config --with-curl=/usr/local/opt/curl`

**Comment by Ankele** [comment]
在UOS上安装PHP5.5.5也遇到此问题，
configure: error: Please reinstall the libcurl distribution -easy.h should be in <curl-dir>/include/curl/
找不到include，
ln -s /usr/include/x86_64-linux-gnu/curl /usr/include/
这个是有效果的！
