### ISSUE TITLE
php类成员变量自增运算时可能会多执行一次。

### ISSUE THREAD

**Issue by kimffy24** [laruence/yar#112]
+ 问题: php类成员变量自增运算时可能会多执行一次。
+ 版本: 
+ + 系统
	```Linux GentooOnParallelsDesktop 4.8.12 #3 SMP Sun Dec 11 16:52:06 HKT 2016 x86_64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz GenuineIntel GNU/Linux```
+ + php-5.6.18 
+ + yar-1.2.5

假设在localhost域名下访问。

server.php 内容

	<?php
	class API {

		public $c2 = 0;

	// 当前构造函数被注释！
	//  public function __construct() { }

		/**
		* the doc info will be generated automatically into service info page.
		* @params
		* @return
		*/
		public function api($parameter, $option = "foo") {

			$this->c2 ++;

			return "This message is from JiefzzLon. \n\$parameter = ".$parameter.", \n\$this->c2 = $this->c2.";
		}
	}
	$service = new Yar_Server(new API());
	$service->handle();

client.php

	<?php
	$client = new Yar_Client("http://localhost/server.php");
	$result = $client->api("小灰灰~");
	var_dump($result);

API类的构造函数被注释时执行访问 `http://localhost/client.php` ，得到

	/server/web/localhost/client.php:4:string 'This message is from JiefzzLon. 
	$parameter = 小灰灰~, 
	$this->c2 = 2.' (length=73)

API类的构造函数不被注释时执行访问 `http://localhost/client.php` ，得到

	/server/web/localhost/client.php:4:string 'This message is from JiefzzLon. 
	$parameter = 小灰灰~, 
	$this->c2 = 1.' (length=73)

API::c2 这个变量在两种情况下的结果为什么会有差别啊？

**Comment by laruence** [comment]
因为API::api会被认为是构造函数(和类同名的方法会被认为是构造函数)

**Comment by kimffy24** [comment]
原来小写也算啊
