### ISSUE TITLE
Uncaught Yar_Client_Transport_Exception: server responsed non-200 code '400'

### ISSUE THREAD

**Issue by si812cn** [laruence/yar#138]
我调用老版本的php5.6的正常
新安装了php7.3版本之后，一直报这个错误
不知道什么问题

**Comment by si812cn** [comment]
我用yar_debug.php调试又是可以的，Yar_Client这个是不是有些问题

**Comment by si812cn** [comment]
php7.2可以，php7.3不行，崩溃中。。。
本想自己编译一下，又懒得动

**Comment by StarCompute** [comment]
遇到了相同的问题。无解

**Comment by StarCompute** [comment]
服务器返回400 错误，基本说明是客户端传递过去的参数错误，俺使用yar_debug.php 做了一下测试，只有在Hearder 中Hostname: \x01\r\n 出现问题的时候会返回400 错误。

**Comment by si812cn** [comment]
我后来用php7.2就好了，先不用php7.3吧

发送自 Windows 10 版邮件应用

发件人: StarCompute
发送时间: 2019年4月13日 23:40
收件人: laruence/yar
抄送: si812cn; Author
主题: Re: [laruence/yar] Uncaught Yar_Client_Transport_Exception: serverresponsed non-200 code '400' (#138)

服务器返回400 错误，基本说明是客户端传递过去的参数错误，俺使用yar_debug.php 做了一下测试，只有在Hearder 中Hostname: \x01\r\n 出现问题的时候会返回400 错误。

**Comment by StarCompute** [comment]
我去稍微看了一下源代码，大概知道问题出在什么地方了。 某种角度来看只要确定不是我自己配置不对之类的原因就好了，这个事情产生一个教训啊，就是有些东西还是自己写更可控啊！

**Comment by si812cn** [comment]
可能作者比较忙吧。
前面版本能用我就先用原来的版本了。
这个源码之前还是基本稳定的，所以我才用了。
不过他那个样例写的比较简单，如果也写的很全面的话，可以很多地方调用。

发送自 Windows 10 版邮件应用

发件人: StarCompute
发送时间: 2019年4月14日 20:37
收件人: laruence/yar
抄送: si812cn; Author
主题: Re: [laruence/yar] Uncaught Yar_Client_Transport_Exception: serverresponsed non-200 code '400' (#138)

我去稍微看了一下源代码，大概知道问题出在什么地方了。 某种角度来看只要确定不是我自己配置不对之类的原因就好了，这个事情产生一个教训啊，就是有些东西还是自己写更可控啊！

**Comment by icoolyy** [comment]
我用的docker部署环境,
NLAMP,
php7.3
yaf 3.0.8
yar 2.0.5
![image](https://user-images.githubusercontent.com/12790860/62455672-8037b000-b7a9-11e9-9938-8360e73e0fee.png)
![image](https://user-images.githubusercontent.com/12790860/62455729-9b0a2480-b7a9-11e9-9b8c-30adc39b40c4.png)
服务端一直这个报错server responsed non-200 code '400'

**Comment by StarCompute** [comment]
版本问题，不要使用最新的版本！ 这个版本的服务端没有问题，客户端有问题，不过可以有替代方案，就是用git 上那个测试用的client类代替




------------------ 原始邮件 ------------------
发件人: "icoolyy"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午5:52
收件人: "laruence/yar"<yar@noreply.github.com>;
抄送: ""<506686@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [laruence/yar] Uncaught Yar_Client_Transport_Exception: serverresponsed non-200 code '400' (#138)




我用的docker部署环境,
 NLAMP,
 php7.3
 yaf 3.0.8
 yar 2.0.5
 
 
 服务端一直这个报错server responsed non-200 code '400'

**Comment by liuxuehua12** [comment]
我把php升级到7.3后，在iis 7.5(windows)和Apache2.4.39(windows)下 yar扩展（yar 2.0.5和2.0.4都测试过）报错：server responsed non-200 code '400'，但是在nginx1.15.11(windows) ,nginx1.16.1(centos7) 和apache2.4.23(windows)下yar扩展使用正常。
不知道作者什么时候可修复这个bug，现在项目已经使用了，希望能升级到7.3可保证开发环境和生产环境一致。

**Comment by liuxuehua12** [comment]
我尝试在windows下编译基于php7.3.10的yar 2.0.5报错（以前在7.0.33下编译yar 2.0.5成功了）。错误提示：
json.obj : error LNK2019: 无法解析的外部符号 __imp_php_json_encode，该符号在函数 php_yar_packager_json_pack 中被引用
json.obj : error LNK2019: 无法解析的外部符号 __imp_php_json_decode_ex，该符号在函数 php_yar_packager_json_unpack 中被引用
libcurl_a.lib(easy.obj) : error LNK2019: 无法解析的外部符号 libssh2_init，该符号在函数 global_init 中被引用
...
...\php_yar.dll : fatal error LNK1120: 308 个无法解析的外部命令

我编译步骤（我已按此步骤成功编译了yaconf扩展）：
1.下载php-sdk-binary-tools 2.1.10、安装好vs2007的c++编译环境、下载好php7.3.10源码
2.执行"phpsdk-vc15-x64.bat"后切换到phpdev/vc15/x64/php-src目录，执行"phpsdk_deps -u"下载了依赖。
3.把yar源码放在phpdev/vc15/x64/pecl目录下
4.在php-src目录内执行"buildconf"
5.再执行"configure --disable-all --enable-cli --enable-pdo  --enable-msgpack=shared --enable-yar=shared"
6.在执行"nmake"

请问上面操作是否有误，能否告诉我下如何在windwos下 正确编译php7.3的yar扩展？

**Comment by visonforcoding** [comment]
php 7.2 同样报错

**Comment by laruence** [comment]
yar本身也是发起一个http请求，如果服务器返回40x， 那就跟正常的http请求40x一样，一般都属于你服务器没有配置好，可以打开nginx的error_log看看原因

**Comment by visonforcoding** [comment]
> yar本身也是发起一个http请求，如果服务器返回40x， 那就跟正常的http请求40x一样，一般都属于你服务器没有配置好，可以打开nginx的error_log看看原因

已解决，亲测 yar_client没有问题。
是我自己瞎，内网端口没写上。
估计大家都是哪里有问题没注意，对于新事务，大家都很容易陷入误区。其实是自己没做对！
