### ISSUE TITLE
Package "yar" Version "2.0.5" does not have REST dependency information available

### ISSUE THREAD

**Issue by jiangliuer326442** [laruence/yar#140]
我在alpine虚拟机中安装yar报错：
`Package "yar" Version "2.0.5" does not have REST dependency information available`
需要安装哪个依赖呢？

**Comment by jiangliuer326442** [comment]
我在alpine虚拟机中安装yar报错：
`Package "yar" Version "2.0.5" does not have REST dependency information available`
需要安装哪个依赖呢？
安装方式：
`pecl install yar`

**Comment by laruence** [comment]
在pecl下载安装包直接自己编译吧
