### ISSUE TITLE
经常报错“curl exec failed 'Timeout was reached'”

### ISSUE THREAD

**Issue by phf0313** [laruence/yar#141]
设置的timeout=6000,connect_timeout=2000

nginx的错误日志为：
2019/05/28 18:50:46 [error] 10760#0: *1450376 FastCGI sent in stderr: "PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.901002]: 719102184: call api 'getMbUserTokenInfo' at (r)'http://core.goushihui168.com/token?city_id=1' with '1' parameters in /alidata/www/goushihui168/data/model/mb_user_token.model.php on line 73
PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.901039]: 719102184: pack request by 'PHP', result len '144', content: 'a:3:{s:1:"i";i:719102184;s:1:"m"' in /alidata/www/goushihui168/data/model/mb_user_token.model.php on line 73
PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.937902]: 719102184: server response content packaged by 'PHP', len '291', content 'a:4:{s:1:"i";i:719102184;s:1:"s"' in /alidata/www/goushihui168/data/model/mb_user_token.model.php on line 73
PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.938606]: 3784590814: call api 'getMemberInfo' at (r)'http://core.goushihui168.com/member?city_id=1' with '2' parameters in /alidata/www/goushihui168/data/model/member.model.php on line 25
PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.938631]: 3784590814: pack request by 'PHP', result len '128', content: 'a:3:{s:1:"i";i:3784590814;s:1:"m' in /alidata/www/goushihui168/data/model/member.model.php on line 25
PHP message: PHP Warning:  [Debug Yar_Client 18:50:45.983850]: 3784590814: server response content packaged by 'PHP', len '1645', content 'a:4:{s:1:"i";i:3784590814;s:1:"s' in /alidata/www/goushihui168/data/model/member.model.php on line 25" while reading response header from upstream, client: 106.15.186.63, server: *.goushihui168.com, request: "GET /mobile/index.php?c=member_payment&a=pay&key=59eccecc869618602249130eca420527&pay_sn=27927077675 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.goushihui168.com"

**Comment by bianpeijiang** [comment]
你的Yar用的是哪个版本？ PHP版本是多少

**Comment by laruence** [comment]
适当增大点超时设置能解决么？
