### ISSUE TITLE
服务端示例更新

### ISSUE THREAD

**Issue by showx** [laruence/yar#142]
`<?php
class API {
    /**
     * the doc info will be generated automatically into service info page.
     * @params
     * @return
     */
    public function api($parameter = '', $option = "foo") {
    	return $parameter;
    }
 
    protected function client_can_not_see() {
    }
}
 
$service = new Yar_Server(new API());
$service->handle();
?>`

例子的$parameter 给个默认值，不然php7中显示异常。

**Comment by laruence** [comment]
你可以弄个PR？
