### ISSUE TITLE
windows环境编译php7.3的yar扩展异常

### ISSUE THREAD

**Issue by liuxuehua12** [laruence/yar#143]
我尝试在windows下编译基于php7.3.10的yar 2.0.5报错（以前在7.0.33下编译yar 2.0.5成功了）。错误提示：
json.obj : error LNK2019: 无法解析的外部符号 __imp_php_json_encode，该符号在函数 php_yar_packager_json_pack 中被引用
json.obj : error LNK2019: 无法解析的外部符号 __imp_php_json_decode_ex，该符号在函数 php_yar_packager_json_unpack 中被引用
libcurl_a.lib(easy.obj) : error LNK2019: 无法解析的外部符号 libssh2_init，该符号在函数 global_init 中被引用
...
...\php_yar.dll : fatal error LNK1120: 308 个无法解析的外部命令

我编译步骤（我已按此步骤成功编译了yaconf扩展）：
1.下载php-sdk-binary-tools 2.1.10、安装好vs2007的c++编译环境、下载好php7.3.10源码
2.执行"phpsdk-vc15-x64.bat"后切换到phpdev/vc15/x64/php-src目录，执行"phpsdk_deps -u"下载了依赖。
3.把yar源码放在phpdev/vc15/x64/pecl目录下
4.在php-src目录内执行"buildconf"
5.再执行"configure --disable-all --enable-cli --enable-pdo --enable-msgpack=shared --enable-yar=shared"
6.在执行"nmake"

请问上面操作是否有误，能否告诉我下如何在windwos下 正确编译php7.3的yar扩展？

**Comment by laruence** [comment]
可以在这里下载： https://pecl.php.net/package/yar/2.0.5/windows
