### ISSUE TITLE
$callinfo的属性具体有哪些?

### ISSUE THREAD

**Issue by feng99** [laruence/yar#158]
详细的看了一遍文档,并搜索了一遍代码目前发现的$callinfo属性
1.$callinfo["method"]  被调用的服务函数名称
2.$callinfo["sequence"] 被调用的服务函数 序列   顺序
3.$callinfo["uri"] 被调用的服务的访问地址

请问还有哪些?
谢谢鸟哥
最近打算使用yar 实现最小技术代价 完成部分业务的拆分.

**Comment by laruence** [comment]
你var_dump一下，就是全部啦
