### ISSUE TITLE
服务端地址页面底部 多出来的信息是哪里来的?

### ISSUE THREAD

**Issue by feng99** [laruence/yar#160]
服务端地址页面底部 多出来的信息是哪里来的?
![image](https://user-images.githubusercontent.com/13182572/81472564-86245b00-922b-11ea-826a-6651fb6f34e3.png)

代码里 我搜索 var_dump
echo
并没有相关代码

**Comment by feng99** [comment]
此信息是否会影响  客户端与服务端交互时的数据包内容?

**Comment by laruence** [comment]
请检查你自己的服务端代码。
