### ISSUE TITLE
header中的provider和token可否自定义

### ISSUE THREAD

**Issue by renxiaotu** [laruence/yar#164]
在yar的header中，有两个32字节的字段，分别是provider和token，虽然每次都传输，但是没有实际意义的。
如果能自定义就好了，然后能统一自定义一个拦截器处理这两个数据，虽说大部分项目用不上，但反正放着也是浪费，即使只能照顾到小众项目也是不错的
一个小脑洞...

**Comment by laruence** [comment]
嗯，原来设计是用来做身份验证的，后来因为都是内部应用，给取消了。。。
你要有兴趣，可以做个PR?
