### ISSUE TITLE
yar 并行调用 不支持设置 timeout

### ISSUE THREAD

**Issue by jianhuihi** [laruence/yar#32]
Yar_Concurrent_Client::call("http://rpcapi******", "getrelkey", array('生产毛坯', 'com'), 'callback', 'error_callback', array(YAR_OPT_TIMEOUT=>1));
 Yar_Concurrent_Client::loop(); //send

getrelkey 函数中sleep 4s

发现设置的YAR_OPT_TIMEOUT 1s没起作用

$client = new Yar_Client("http://rpcapi**************");
$client->SetOpt(YAR_OPT_TIMEOUT, 1);
$result = $client->getrelkey(array('生产毛坯', 'com'));
var_dump($result);

这样设置的1s能看到效果

另外php.ini里面设置1000也能看到效果

系统max os
PHP Version 5.3.28
curl
cURL support    enabled
# cURL Information    7.33.0

yar
yar support enabled
Version 1.2.4-dev

Directive   Local Value Master Value
yar.allow_persistent    0   0
yar.connect_timeout 1000    1000
yar.content_type    application/octet-stream    application/octet-stream
yar.debug   0   0
yar.expose_info On  On
yar.packager    php php
yar.timeout 5000    5000
yar.transport   curl    curl

盼回复

**Comment by sursir** [comment]
@laruence 

鸟叔。 我正好遇到这个问题。
Multi 单个timeout不起作用。 
如果设置multi的 option 有两个问题 
> 1. `5.5以上才支持`
> 2. `没有找到设置超时的选项`,  多行设置是 CURLM_打头的 但是我在手册上没看到类似设置超时的项

... 感觉有点坑
求指教怎么可以设置并行超时

**Comment by sursir** [comment]
接上 我说的并不是yar  而是鸟叔的另一项目 PHP

**Comment by firenzelei** [comment]
i have same question with you , and the solution is

ini_set("yar.connect_timeout", 1000);
ini_set("yar.timeout", 1000);
