### ISSUE TITLE
[SAE]yar报错“server info is not allowed to access”

### ISSUE THREAD

**Issue by chengs** [laruence/yar#36]
发现SAE的phpinfo中支持yar，信息如下：

| yar support | enabled |
| --- | --- |
| Version | 1.2.3 |

| Directive | Local Value | Master Value |
| --- | --- | --- |
| yar.allow_persistent | 0 | 0 |
| yar.connect_timeout | 1000 | 1000 |
| yar.content_type | application/octet-stream | application/octet-stream |
| yar.debug | Off | Off |
| yar.expose_info | no value | no value |
| yar.packager | php | php |
| yar.timeout | 5000 | 5000 |
| yar.transport | curl | curl |

于是乎按照说明写了一段代码进行测试，

``` php
<?php

class API {
    /**
     * the doc info will be generated automatically into service info page.
     * @params 
     * @return
     */
    public function some_method($parameter, $option = "foo") {
    }

    protected function client_can_not_see() {
    }
}

$service = new Yar_Server(new API());
$service->handle();

?>
```

结果报如下错误：

```
Fatal error: Uncaught exception 'Yar_Server_Exception' with message 'server info is not allowed to access' in /data1/www/htdocs/407/bonjourchen/1/yar.php:17 Stack trace: #0 /data1/www/htdocs/407/bonjourchen/1/yar.php(17): Yar_Server->handle() #1 {main} thrown in yar.php on line 17
```

估计是SAE的权限不允许，server info is not allowed to access，但是没办法改动php.ini，请问有什么办法么？

**Comment by syjsu** [comment]
谢谢 解决了一个我一直疑惑的问题

**Comment by chengs** [comment]
@syjsu 不客气～
