### ISSUE TITLE
yar 协议疑问？

### ISSUE THREAD

**Issue by gyf19** [laruence/yar#38]
个人写想一个yar 的  golang server  。  通过抓包了解yar协议， 发现 request信息  和 response 信息 都有一个90长度的内容。  请问90长度是什么内容？

![20141216151558](https://cloud.githubusercontent.com/assets/233857/5449791/a345bf92-8536-11e4-9190-5e0c8dae70bc.jpg)

**Comment by gyf19** [comment]
协议头 没有发现 序列化格式的信息？

**Comment by gyf19** [comment]
readme 的协议头 64位系统长度是82 ，还有8个字节是什么呢？ 

 unsigned int   id;            // transaction id
    unsigned short version;       // protocl version
    unsigned int   magic_num;     // default is: 0x80DFEC60
    unsigned int   reserved;
    unsigned char  provider[32];  // reqeust from who
    unsigned char  token[32];     // request token, used for authentication
    unsigned int   body_len;      // request body len

**Comment by leeeboo** [comment]
@gyf19 http://blog.weixinhost.com/wei-ming-ming/ 可以看一下这个。

**Comment by gyf19** [comment]
xiexie
