### ISSUE TITLE
我想吧yar融合入yaf中 可是报错

### ISSUE THREAD

**Issue by iranw** [laruence/yar#44]
鸟哥 你好
我想做一个rpc接口 用yaf+yar实现
但是 我在控制器里写了一下代码
------------------------------
class IndexController Extends Yaf_Controller_Abstract
{
    private function init() {
        $service = new Yar_Server(new static());
        $service->handle();

    }

    public function loginAction() {//默认Action
    }
}

但是返回错误信息如下
Warning: Yaf_Controller_Abstract::__construct() expects at least 3 parameters, 0 given in D:\wwwroot\FrameWork\yaf-yar\app\application\modules\User\controllers\Index.php on line 14
想问问鸟哥有什么好方法推荐没

**Comment by yovei** [comment]
这个错 和YAR 没关系吧？

**Comment by yovei** [comment]
你自己的用法有错  直接用 $this 不可以吗

**Comment by iranw** [comment]
代表本类 用self 但是用new $this 没这个用法把？

**Comment by yovei** [comment]
$service = new Yar_Server($this);

**Comment by laruence** [comment]
这个和Yar应该是没关系,  不过我没明白, 你覆盖了Yaf_Controller的construct了么? 为啥提示是yaf_controller的参数不对

**Comment by iranw** [comment]
谢谢鸟哥回复  为什么提示参数问题 我也一直没弄明白 现在这个问题已经通过其他方法解决
等yaf+yar组合的接口框架基本成形 还需要鸟哥多多指教
