### ISSUE TITLE
有支持lua的计划么  服务端

### ISSUE THREAD

**Issue by quqiufeng** [laruence/yar#53]
配合 openrestry 玩,很合适啊, 它专做api

**Comment by laruence** [comment]
我没有, 你做一个开源呗 嘿嘿 :)

**Comment by quqiufeng** [comment]
没思路  基于socket tcp, php这边调用地址是 "tcp://127.0.0.1:80" ?

ngx_lua tcp demo  然后遵循yar 协议?
location /cosocket {
        default_type "text/plain";
        content_by_lua '
        local sock = ngx.socket.tcp()
        sock:settimeout(1000)
        local ok, err = sock:connect("127.0.0.1", 12000)
        if not ok then
            ngx.say("failed to connect: ", err)
            return
        end
        local bytes, err = sock:send("flush_all")
        ngx.say(bytes,err)
        if not bytes then
            ngx.say("failed to send query: ", err)
            return
        end
       local line, err = sock:receive()
        if not line then
            ngx.say("failed to receive a line: ", err)
            return
        end
        ngx.say("result: ", line)
        ';
      }
                                                                                                                                                                                                                                                                                                                                                                                       
    }
}

**Comment by quqiufeng** [comment]
ngx_lua 服务端代码
 
location /test
 {
                 content_by_lua '
                    ngx.req.read_body()
                    local body    = ngx.req.get_body_data()
                    local header  = string.sub(body,1,82)
                    local package = string.sub(body,83,90)
                    local _body   = string.sub(body,91)
                    local cjson   = require "cjson"
                    local result  = cjson.decode(_body)
                    local id      = result.i
                    local respone = {i=id,s=200,r="hehe",o="hehe",e="error"}
                    local result  = cjson.encode(respone)
                    local sendout = table.concat({header,package,result})
                    ngx.log(ngx.ERR,sendout)
                    ngx.say(sendout)
                    return
                ';
}

client 代码

$client = new Yar_Client("http://localhost/test");
$client->SetOpt(YAR_OPT_PACKAGER, "json");
$result = $client->api("quqiufeng@gmail.com");
print_r($result);

报错信息

Fatal error: Uncaught exception 'Yar_Client_Exception' with message 'error' in /var/www/caijia/test.php:5 Stack trace: #0 /var/www/caijia/test.php(5): Yar_Client->__call('api', Array) #1 /var/www/caijia/test.php(5): Yar_Client->api('quqiufeng@gmail...') #2 {main} thrown in /var/www/caijia/test.php on line 5

求帮助!!!

**Comment by laruence** [comment]
你没有错误就不要返回e啊.... 你都返回e(exception)了, 客户端当然如实的抛出异常了 :<

**Comment by quqiufeng** [comment]
哦 哦  搞定了

http://quqiufeng.blog.163.com/blog/static/24255301420156273143583/

**Comment by laruence** [comment]
r是return, o是output, 一般用不到o(就是直接输出)

**Comment by quqiufeng** [comment]
http://quqiufeng.blog.163.com/blog/static/242553014201569104927633/

再来一个 msgpack 打包数据的例子
