### ISSUE TITLE
Failed test with PHP 7.0.0beta2 / 32bits

### ISSUE THREAD

**Issue by remicollet** [laruence/yar#56]
ON x86_64 evreything seems ok.

On i386, 1 failed test.

    TEST 10/17 [tests/010.phpt]
    ========DIFF========
    001+ Warning: [Debug Yar_Client 11:7:20.380463]: -496872129: call api 'normal' at (r)'http://localhost:8964/' with '1' parameters in /builddir/build/BUILD/php-pecl-yar-1.2.5/NTS/tests/010.php on line 8
    001- Warning: [Debug Yar_Client %s]: %d: call api 'normal' at (r)'%s' with '1' parameters in %s010.php on line %d
    003+ Warning: [Debug Yar_Client 11:7:20.380482]: -496872129: pack request by 'PHP', result len '86', content: 'a:3:{s:1:"i";i:-496872129;s:1:"m' in /builddir/build/BUILD/php-pecl-yar-1.2.5/NTS/tests/010.php on line 8
    003- Warning: [Debug Yar_Client %s]: %d: pack request by 'PHP', result len '%d', content: 'a:3:{s:1:"i";i:%s' in %s010.php on line %d
    005+ Warning: [Debug Yar_Client 11:7:20.380901]: -496872129: server response content packaged by 'PHP', len '65', content 'a:3:{s:1:"i";i:-496872129;s:1:"s' in /builddir/build/BUILD/php-pecl-yar-1.2.5/NTS/tests/010.php on line 8
    005- Warning: [Debug Yar_Client %s]: %d: server response content packaged by 'PHP', len '%d', content 'a:3:{s:1:"i";i%s' in %s010.php on line %d
    ========DONE========
    FAIL Check for yar debug [tests/010.phpt]

**Comment by remicollet** [comment]
Should request->id by unsigned ?

**Comment by laruence** [comment]
hmm, right, must be some printf issue

**Comment by remicollet** [comment]
I confirm, the bug is fixed.
Thanks
