### ISSUE TITLE
Yar_Client能添加自定Header或Cookie吗？

### ISSUE THREAD

**Issue by boboweb** [laruence/yar#60]
服务端的代码依赖Header和Cookie，Yar_Client能添加自定Header或Cookie吗？

**Comment by neverlee** [comment]
用这个扩展的client的话要改扩展的代码才行

**Comment by laruence** [comment]
不行, 因为Yar不仅仅是面向HTTP的, 这些你只能通过参数传递了. 或者url中的query string

**Comment by laruence** [comment]
鉴于这个需求比较多, 我实现了这个功能, 如果有需要可以下载主干代码使用,  下个版本初步打算下个月再发布
