### ISSUE TITLE
php5.6 Yar服务端500

### ISSUE THREAD

**Issue by neverlee** [laruence/yar#61]
不知道大家有没有遇到这样的问题
Ubuntu14.04上用的ppa:ondrej/php5-5.6的php。
php及php5-fpm版本信息
PHP 5.6.14-1+deb.sury.org~trusty+1 (fpm-fcgi)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
yar手动编译，使用过1.2.3, 1.2.4及commit baefc15424a3b01178b1dba65dc0e491b08da297的版本。
server：-----------------------------
<?php
class File {
    public function add($data = array()) {
        var_dump($data);
        $return = array("state" => 1, "message" => "", "code" => 0);
        return $return;
    }
}
$service = new Yar_Server(new File());
$service->handle();
client：-----------------------------
<?php
$data = array (
    'parent_id' => 0,
    'sha1' => 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'file_name' => 'sxxx_n_oxdcfohxxjjyyybfykrinraddon.jpg',
    'file_description' => '',
    'file_size' => 59391,
);
$url = "http://127.0.0.1/file.php";
$client = new Yar_Client($url);
$result = $client->add($data);
var_dump($result);
测试脚本中，当client中的$data中字段比较少时，整个运行正常。但当$data字段较多时，比如说有一二十个，server端就会500，我用curl模拟client请求看，只能拿到nginx返回的500了。当然，当$data中字段达到一定数量时导致500时。
综上讲，就是当输出及return的数据量比较大时就500。我测试过在client设置打包模式为json,php都这样，但在ubuntu14.04自带的php5.59上使用正常。
怀疑是在这个版本的php上，序列化数据或返回数据时内存溢出。
正在研究yar源码，就这个问题，望大牛们能指定一二。

**Comment by laruence** [comment]
看看nginx/php的错误日志, 500错误的原因是啥就很容易解决了

**Comment by neverlee** [comment]
发现问题了，yar_server.c里的handle函数里，raw_data释放掉时，pkg_name和payload这两个指向这一块内存块的变量还在被使用。我pull了一个request
https://github.com/laruence/yar/pull/62
麻烦你抽个时间确认下。

**Comment by neverlee** [comment]
已解决
