### ISSUE TITLE
多次调用loop时，会重复请求

### ISSUE THREAD

**Issue by haython** [laruence/yar#69]
Yar_Concurrent_Client::call($url, 'lists');
Yar_Concurrent_Client::call($url, 'lists');
Yar_Concurrent_Client::loop();

Yar_Concurrent_Client::call($url, 'lists');
Yar_Concurrent_Client::call($url, 'lists');
Yar_Concurrent_Client::loop();

第一次loop时会发起2次请求，第二次loop时会发起4次请求

**Comment by laruence** [comment]
使用Yar_Concurrent_Client::reset(); http://php.net/manual/en/yar-concurrent-client.reset.php
