### ISSUE TITLE
php7.0环境下调用yar报错server responsed non-200 code '403'

### ISSUE THREAD

**Issue by vancett** [laruence/yar#70]
系统:centos 7，
php:版本:7.0
yar:版本2.0.0
错误详情：
Type: Yar_Client_Transport_Exception
Message: server responsed non-200 code '403'

**Comment by laruence** [comment]
服务端返回403， 看看你服务端的错误日志。 请求路径啥的估计不对

**Comment by vancett** [comment]
服务端代码
class Workloader {
    public function start($a) {
        return array('error' => -1, 'data' => array('result' => -1));
    }
}
nginx 日志
127.0.0.1 - - [29/Dec/2015:22:24:26 +0800] "POST /workloader HTTP/1.1" 403 1143 "-" "PHP Yar Rpc-2.0.0"

此前php5.5版本调用成功的日志为:
144 192.168.10.152 - - [29/Dec/2015:21:01:04 +0800] "POST /workloader HTTP/1.1" 200 1871 "-" "PHP Yar Rpc-1.2.4"

**Comment by vancett** [comment]
@laruence 谢谢惠哥，问题原因找到了，是我在服务器端字符过滤上的原因，我把CI框架里的字符过滤功能关闭就好了。

**Comment by vancett** [comment]
为啥一个字符过滤的原因会让程序的调用出错，那有哪些特殊字符是我要调用过程中特别需要注意的呢。

**Comment by laruence** [comment]
这个要看具体case的是啥

**Comment by visonforcoding** [comment]
> 系统:centos 7，
> php:版本:7.0
> yar:版本2.0.0
> 错误详情：
> Type: Yar_Client_Transport_Exception
> Message: server responsed non-200 code '403'

同样的问题

**Comment by laruence** [comment]
你看服务器日志啊，http请求403，你服务器没设置好。

**Comment by visonforcoding** [comment]
> > 系统:centos 7，
> > php:版本:7.0
> > yar:版本2.0.0
> > 错误详情：
> > Type: Yar_Client_Transport_Exception
> > Message: server responsed non-200 code '403'
> 
> 同样的问题

看错了，我的问题是404. 其他人也遇到了
