### ISSUE TITLE
 Fatal error: Uncaught exception 'Yar_Server_Exception' with message 'server info is not allowed to access' 

### ISSUE THREAD

**Issue by zhaoyong2006** [laruence/yar#77]
打算GET请求服务端不打印yar输出的信息，刚刚收鸟哥指点，做如下修改
php.ini中设置 yar.expose_info = 0

但页面报错：

`Fatal error: Uncaught exception 'Yar_Server_Exception' with message 'server info is not allowed to access' in /data/test/yar_demo/test.php:18 Stack trace: #0 /data/test/yar_demo/test.php(18): Yar_Server->handle() #1 {main} thrown in /data/test/yar_demo/test.php on line 18`

这里报的(yar_server.c 678行)：

```
if (!method || strncasecmp(method, "POST", 4)) {
            if (YAR_G(expose_info)) {
                php_yar_server_info(executor TSRMLS_CC);
                RETURN_TRUE;
            } else {
                zend_throw_exception(yar_server_exception_ce, "server info is not allowed to access", YAR_\
ERR_FORBIDDEN TSRMLS_CC);
                return;
            }
        }
```

请问怎么不报错，在线等~

**Comment by laruence** [comment]
try  catch下啊
