### ISSUE TITLE
php7 yar扩展文档没出来，也不报错

### ISSUE THREAD

**Issue by joshua317** [laruence/yar#84]
使用php7的环境，yar扩展也安装成功了，而且接口是可以打印出来，只不过文档没出来
安装步骤：
yar扩展安装yar.so
        cd /app/soft
        wget http://pecl.php.net/get/yar-2.0.0.tgz
        tar zxvf yar-2.0.0.tgz
        cd yar-2.0.0
        /app/php7/bin/phpize
        ./configure --with-php-config=/app/php7/bin/php-config --enable-msgpack
        make && make install

![1](https://cloud.githubusercontent.com/assets/12826232/16353905/ab9d7488-3ab5-11e6-9fe4-ec820fe0b77d.png)
![2](https://cloud.githubusercontent.com/assets/12826232/16353908/b0517df8-3ab5-11e6-808b-099f76021f35.png)

**Comment by laruence** [comment]
安装最新的版本

**Comment by joshua317** [comment]
解决了，谢鸟哥
