### ISSUE TITLE
yar在php7下有内存泄漏

### ISSUE THREAD

**Issue by zhanglei** [laruence/yar#89]
鸟哥，yar在php-7.0.10下好像有内存泄漏，用的是master最新代码

![image](https://cloud.githubusercontent.com/assets/241508/18621652/3611d852-7e59-11e6-85b6-a3d71624c4b4.png)

![image](https://cloud.githubusercontent.com/assets/241508/18621660/480374a8-7e59-11e6-835c-64bf31600ec5.png)

**Comment by laruence** [comment]
怎么复现?

**Comment by laruence** [comment]
噢, 你用的是Socket. 修复了

**Comment by zhanglei** [comment]
好的，我试下，鸟哥这修bug速度真赞！

**Comment by zhanglei** [comment]
鸟哥，昨天那个代码改的有问题

![image](https://cloud.githubusercontent.com/assets/241508/18654781/677db97a-7f16-11e6-9eda-64d12cc61699.png)
close时已经free内存了

之前的内存泄漏是偶现

**Comment by laruence** [comment]
好 , 我继续看看

**Comment by laruence** [comment]
重新修复了下, 再试试

**Comment by zhanglei** [comment]
好的，我试试
