### ISSUE TITLE
socket 方式调用收发包没有做php_stream_eof检查

### ISSUE THREAD

**Issue by zhanglei** [laruence/yar#92]
鸟哥：

在使用socket方式长连接调用时php_yar_socket_send和php_yar_socket_exec函数没有做收发包php_stream_eof检查

查看文档 https://github.com/php/php-src/pull/1456看到php 5.6.13版本以下内核在进行长连接检查有bug

**Comment by laruence** [comment]
有头部的长度字段,  不需要检查eol
