### ISSUE TITLE
关于setOpt使用

### ISSUE THREAD

**Issue by wuent** [laruence/yar#94]
yar：1.2.5  php 5.6.20
var_dump($client->setOpt(YAR_OPT_PACKAGER, 1));
var_dump($client->setOpt(YAR_OPT_PACKAGER, array()));

报错提示：
Message: Yar_Client::setOpt(): expects a string packager name
Message: Yar_Client::setOpt(): expects a string packager name
请问这是为什么？我是安装tests里的配置写的。
setOpt()具体怎么使用，有详细文档吗？

**Comment by laruence** [comment]
http://php.net/manual/en/yar-client.setopt.php
