### ISSUE TITLE
php7.1 环境下的 同时使用YAF  和YAR 结果报错了  内存耗尽

### ISSUE THREAD

**Issue by archoncap** [laruence/yar#98]
class IndexController extends Yaf_Controller_Abstract {
	
	/** 
	* 构造函数
	* 
	* @param  $type 整型 类型（1: 类型a 2：类型b 3:类型c 4:类型d 5:类型e）
	* 	
	* @return $rows 数组 返回对应的数据包
	*/
	Public function indexAction(){	
		$server = new Yar_Server($this);
		$server->handle();
	}

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1936288885 bytes) in /www/wwwroot/    

按说明书的方法写没问题 ,  我这样用是  YAF的问题 还是YAR的问题 ?

代码不变切换成5.6的就是OK的 , 没有任何的报错的

**Comment by laruence** [comment]
你能不能弄一个可重现的项目(打个包), 我本地复现下, thanks

**Comment by archoncap** [comment]
php7.1 用YAF的最新版本,然后在控制器方法中 调用YAR_server 方法就会就报内存耗尽的错误. 但是PHP切换到的php5.6就没有这么错误 .  所以不清楚是哪里的问题 ,代码的话我打包一个发大神邮箱?

**Comment by archoncap** [comment]
$server->handle(); 这一行代码 会报错的

**Comment by archoncap** [comment]
鸟哥你好  项目地址是 https://github.com/archoncap/apidemo
有问题的程序文件是 https://github.com/archoncap/apidemo/blob/master/APP/controllers/rpc.php   的  $server->handle();    运行的环境是 centos 6.8/64bit    php 是 php7.1 或者7.0 下面使用yaf 然后调用 yar 就会有报错 , 错误大致就是 内存耗尽...   Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1936288885 bytes) in      但我感觉可能是程序版本里 的 handle() 陷入死循环了. 请大神指教!小弟膜拜!

**Comment by archoncap** [comment]
感谢鸟哥 百忙之中抽空视察github 倍感荣幸!

**Comment by laruence** [comment]
已经修复,  最近发布新版, 你要是着急, 可以先用仓库里的代码 , :)

**Comment by archoncap** [comment]
3Q very much!
